news: Nix development environment and package
OSGeo/grass-website pull request #440
Opened 2024-07-06 09:01 UTC by imincik

Add "Nix development environment and package" news.

2024-07-06 12:17 UTC, veroandreo requested changes
Thanks @imincik !! Great addition! Let's wait with this news until the doc is merged.

2024-07-06 12:17 UTC, veroandreo commented on content/news/2024_06_07_Nix_environment_and_package_added.md
> +Nix development environment provides a stable and reproducible environment
```suggestion
The Nix development environment provides a stable and reproducible environment
```

2024-07-06 12:17 UTC, veroandreo commented on content/news/2024_06_07_Nix_environment_and_package_added.md
> +for all developers and can significantly simplify onboarding process of new
```suggestion
for all developers and can significantly simplify the onboarding process of new
```

2024-07-06 12:17 UTC, veroandreo commented on content/news/2024_06_07_Nix_environment_and_package_added.md
> +To start hacking on GRASS, run `nix develop` command in source code root
```suggestion
To start hacking on GRASS, run `nix develop` command within the source code root
```

2024-07-06 12:17 UTC, veroandreo commented on content/news/2024_06_07_Nix_environment_and_package_added.md
> +dependencies with instructions how to build and test the code.
```suggestion
dependencies and get instructions on how to build and test the code.
```

2024-07-06 12:17 UTC, veroandreo commented on content/news/2024_06_07_Nix_environment_and_package_added.md
> +On the other hand, possibility to run GRASS directly from a Git
```suggestion
On the other hand, the possibility to run GRASS directly from the Git
```

2024-07-06 12:17 UTC, veroandreo commented on content/news/2024_06_07_Nix_environment_and_package_added.md
> +GRASS on any Linux distribution immediately when new version is out.
```suggestion
source code improves the feedback loop during development and will allow to install
GRASS on any Linux distribution immediately after a new version is out.
```

2024-07-06 12:17 UTC, veroandreo commented on content/news/2024_06_07_Nix_environment_and_package_added.md
> +To run latest development version of GRASS directly from a Git source code, run
```suggestion
To run the latest development version of GRASS directly from the Git source code, run
```

2024-07-06 12:17 UTC, veroandreo commented on content/news/2024_06_07_Nix_environment_and_package_added.md
> +   width="70%" style="float:center;padding-left:10px;padding-top:20px">
```suggestion
   width="90%" style="float:center;padding-left:10px;padding-top:20px">
```

2024-07-06 12:17 UTC, veroandreo commented on content/news/2024_06_07_Nix_environment_and_package_added.md
> +To install it, run `nix profile install github:OSGeo/grass#grass`.
```suggestion
If you want to install GRASS instead, run `nix profile install github:OSGeo/grass#grass`.
```

2024-07-06 12:17 UTC, veroandreo commented on content/news/2024_06_07_Nix_environment_and_package_added.md
> +*Ivan Mincik and Veronica Andreo*
```suggestion
*Ivan Mincik*
```

2024-07-09 14:05 UTC, neteler commented on content/news/2024_06_07_Nix_environment_and_package_added.md
> +### You can now develop and run GRASS with Nix
```suggestion
### You can now develop and run GRASS GIS with Nix
```

2024-07-09 14:06 UTC, neteler commented on content/news/2024_06_07_Nix_environment_and_package_added.md
> +### You can now develop and run GRASS with Nix
(at least in the section titles...)

2024-07-15 13:29 UTC, veroandreo approved these changes

2024-07-15 13:30 UTC, merged

2024-07-16 07:54 UTC, imincik commented
Still doesn't [appear in on the website](https://grass.osgeo.org/news/) . Is it OK ?

2024-07-16 10:31 UTC, veroandreo commented
> Still doesn't [appear in on the website](https://grass.osgeo.org/news/) . Is it OK ?

@neteler would you mind checking in the server side? 🙏🏼 It was building just fine locally

2024-07-16 12:14 UTC, neteler commented
I gave the cronjob a kick, now there:

https://grass.osgeo.org/news/2024_06_07_nix_environment_and_package_added/

2024-07-16 12:23 UTC, veroandreo commented
> I gave the cronjob a kick, now there:
> 
> https://grass.osgeo.org/news/2024_06_07_nix_environment_and_package_added/

Thanks! The code highlighting changes I did were ineffective it seems... This is how it looked like locally:

![image](https://github.com/user-attachments/assets/fc84adf3-6081-4629-ae9b-b959f45b0897)

2024-07-16 12:58 UTC, veroandreo commented
Yes, indeed! I changed browser and it looks good there! Cool! Thanks! And sorry for the noise :)